-- ============================================================
-- Seed Wisconsin Dog Parks from BringFido
-- Generated: 2026-02-13T20:57:32.662Z
-- Total parks: 20
-- Source: https://www.bringfido.com/attraction/
-- ============================================================

-- Clear existing WI parks first (optional - comment out if you want to keep existing)
-- DELETE FROM parks WHERE address LIKE '%, WI %';

INSERT INTO parks (name, description, latitude, longitude, address, city, state, amenities, is_fenced, has_water, has_shade)
VALUES
  ('Dog Park at Yahara Heights County Park', 'Dogs can play off leash in the 20-acre dog park at Yahara Heights County Park in Waunakee, WI, which features ample grassy space and water for Fido to dip his paws into. Please note dog permits are required.', 43.1546004, -89.40536, '5488 Catfish Ct, Waunakee, WI 53597', 'Waunakee', 'WI', ARRAY['water_access']::text[], false, true, false),
  ('Burlington Dog Park', 'Fido is invited to play at Burlington Dog Park in Wisconsin. Dogs of all sizes are welcome to join for socialization. Amenities include chairs along with a waste and water station.', 42.669813, -88.2671306, '480 S Calumet St, Burlington, WI 53105', 'Burlington', 'WI', ARRAY['water_access']::text[], false, true, false),
  ('Platteville Community Dog Park', 'Nestled against the Rountree Branch stream in Platteville, WI, the five-acre Platteville Community Dog Park provides a safe and spacious area for dogs to frolic and play. It''s a fenced-in off-leash area, with separate sections for small and large dogs, a wooded walking path, poop disposal stations, picnic tables, parking and a porta-potty.', 42.7323588, -90.4648979, '946 Valley Rd, Platteville, WI 53818', 'Platteville', 'WI', ARRAY['fenced', 'parking', 'picnic_tables', 'restroom', 'separate_areas', 'shade_trees', 'walking_trails', 'waste_bags']::text[], true, false, true),
  ('Tails n Trails Dog Park', 'Fido is invited to play at the Tails n Trails Dog Park in Milton, WI. This off-leash facility has two separate areas for small and large dogs. Amenities include water, a walking trail and off-street parking.', 42.7735835, -88.9666275, '862 W High St, Milton, WI 53563', 'Milton', 'WI', ARRAY['parking', 'separate_areas', 'shade_trees', 'walking_trails', 'water_access']::text[], false, true, true),
  ('Waupaca County Dog Park', 'Shade trees, benches, picnic tables, and agility equipment are amenities of the Waupaca County Dog Park. This two-acre fenced-in recreation space is a local favorite among the Waupaca, WI, community.', 44.3455096, -89.0965865, '601 Lakeside Pkwy, Waupaca, WI 54981', 'Waupaca', 'WI', ARRAY['agility_equipment', 'benches', 'fenced', 'picnic_tables', 'shade_trees']::text[], true, false, true),
  ('Off-Leash Dog Area at Mead Park', 'Fido is invited to play at the off-leash dog area at Mead Park in Stevens Point, WI. The beach opens 30 minutes before sunrise, and your furry friend can play until 11:00 PM daily. Owners must be within the fenced-in area with a leash readily available while watching their pup. Park users without an animal may also use this beach.', 44.5217524, -89.5931195, '1201 W Whitney St, Stevens Point, WI 54481', 'Stevens Point', 'WI', ARRAY['fenced', 'water_access']::text[], true, true, false),
  ('Paws & Play Dog Park', 'Paws & Play Dog Park is a 4.5-acre fenced-in area in Marshfield, WI. The park is relied on donations and has two separate areas for small and large dogs. Amenities include waste stations, picnic tables and water during the warmer months.', 44.6493446, -90.1722062, 'E 21st St & S Peach Ave, Marshfield, WI 54449', 'Marshfield', 'WI', ARRAY['fenced', 'picnic_tables', 'separate_areas', 'waste_bags', 'water_access']::text[], true, true, false),
  ('Hudson Dog Park', 'Bring Fido to blow off some steam at the Hudson Dog Park in Hudson, WI. This two-acre pup recreation area is fully fenced and has waste bags on site. All dogs must be licensed in the municipality where the owner and pet reside.', 44.9789803, -92.7217686, '908 Carmichael Rd, Hudson, WI 54016', 'Hudson', 'WI', ARRAY['fenced', 'waste_bags']::text[], true, false, false),
  ('Merrill Dog Park at the MARC', 'Fido is invited to play at the Merrill Dog Park at the MARC in Wisconsin. The off-leash area is 2.5 acres and features a separate section for small dogs. If the park is busy, they have pathways connecting to Council Grounds State Park.', 45.1915025, -89.7259475, '1100 Marc Dr, Merrill, WI 54452', 'Merrill', 'WI', ARRAY['separate_areas', 'walking_trails']::text[], false, false, false),
  ('Laura & Peter Mossakowski Family Dog Park', 'Fido will love playing at the Laura & Peter Mossakowski Family Dog Park in Bellevue, WI. This 6.5-acre recreation space is a place where furry friends have a place to run, roll around in the mud, meet new four-legged friends and even catch a ball or a Frisbee. Note that permits are required to use this dog park.', 44.460631, -88.011728, '2282 Bellevue St, Bellevue, WI 54311', 'Bellevue', 'WI', ARRAY[]::text[], false, false, false),
  ('River Falls Dog Park', 'Bring your pup to socialize and get some exercise at the River Falls Dog Park in River Falls, WI. This 16-acre fenced off-leash pup recreation area features separate sections for small and large dogs, picnic tables, benches and dog waste stations. No running water is available, so make sure to bring some for Fido! There is plenty of parking on site.', 44.8323622, -92.6482193, 'W10225 County Rd FF, River Falls, WI 54022', 'River Falls', 'WI', ARRAY['benches', 'fenced', 'parking', 'picnic_tables', 'separate_areas', 'waste_bags', 'water_access']::text[], true, false, false),
  ('Sister Bay Dog Park', 'If Fido needs a place to stretch his legs, bring him for a romp at the Sister Bay Dog Park in Sister Bay, WI. Entirely fenced in and equipped with picnic tables and mutt mitts, the park is open year-round, from dawn until dusk, and is free to the public.', 45.18901, -87.1101437, '2124 Autumn Ct, Sister Bay, WI 54234', 'Sister Bay', 'WI', ARRAY['fenced', 'picnic_tables', 'waste_bags']::text[], true, false, false),
  ('Bark & Brew', 'Bark & Brew is a pet-friendly spot in Howard, WI. The first of its kind, this off-leash, indoor/outdoor, climate-controlled establishment has a dog menu and delicious beverages for humans. Though they do not sell human food, you can bring in your own or have it delivered from your favorite takeout spot!', 44.5644788, -88.0799234, '2514 Glendale Ave, Howard, WI 54313', 'Howard', 'WI', ARRAY[]::text[], false, false, false),
  ('The City of Superior Dog Park', 'Fido is invited to play at The City of Superior Dog Park near the Millennium Trailhead in Wisconsin. This off-leash area has a two-way entrance and various trees spread throughout for shade. Amenities also include benches and waste stations.', 46.7050166, -92.1236832, 'N 28th St, Superior, WI 54880', 'Superior', 'WI', ARRAY['benches', 'shade_trees', 'waste_bags']::text[], false, false, true),
  ('Point Dog Park', 'Fido is invited to play at Point Dog Park in Stevens Point, WI. The off-leash facility contains two separate sections that are approximately 30 acres. Amenities include trails, wooded areas, benches and waste stations.', 44.5096973, -89.5810604, '601 Mason St, Stevens Point, WI 54481', 'Stevens Point', 'WI', ARRAY['benches', 'separate_areas', 'shade_trees', 'walking_trails', 'waste_bags']::text[], false, false, true),
  ('Viroqua Bark Park', 'Fido is invited to play at Viroqua Bark Park in Wisconsin. The off-leash facility is separated into two sections for large and small dogs. Amenities include solar lights, picnic tables and benches. Please note there is no water source in this park, so pack some for your pup.', 43.5717494, -90.8797659, '700 Power Dr, Viroqua, WI 54665', 'Viroqua', 'WI', ARRAY['benches', 'lighting', 'picnic_tables', 'separate_areas', 'water_access']::text[], false, false, false),
  ('Florence Bark Park', 'Bring your pup to the Florence Bark Park, a one-acre fenced-in off-leash dog park in Florence, WI. There are benches for humans and plenty of space for your pup to run, socialize and get some exercise.', 45.9224395, -88.2639785, '5628 Forestry Dr, Florence, WI 54121', 'Florence', 'WI', ARRAY['benches', 'fenced']::text[], true, false, false),
  ('Marvin & Marie Schweer''s Dog Park', 'Marvin & Marie Schweer''s Dog Park is an off-leash recreation space in DeForest, WI. The park ensures pups play safely and comfortably with two separate fenced-in areas for large and small dogs. The park is free for residents, but visitors may pay a one-time or annual fee to let Fido play.', 43.2600591, -89.3381002, '700 Stevenson St, De Forest, WI 53532', 'De Forest', 'WI', ARRAY['fenced', 'separate_areas']::text[], true, false, false),
  ('Webster Community Dog Park', 'Fido is invited to play at the Webster Community Dog Park in Wisconsin. This off-leash facility has two separate sections for small and large dogs and a training area. Amenities include waste stations and double-gated entrances for safety.', 45.8676535, -92.3647619, '27383 Hwy 35 N, Webster, WI 54893', 'Webster', 'WI', ARRAY['double_gated', 'separate_areas', 'training_area', 'waste_bags']::text[], false, false, false),
  ('Spring Green Dog Park', 'Bring Fido to blow off some steam at the Spring Green Dog Park in Spring Green, WI. This off-leash pup recreation area features separate sections for small and large dogs, and is a great place to bring your pooch to play, have fun and make some new friends. Dog owners are reminded to keep an eye on their pup as they play and to clean up any mess that they leave behind.', 43.1738239, -90.081069, 'S12947 Shifflet Rd, Spring Green, WI 53588', 'Spring Green', 'WI', ARRAY['separate_areas']::text[], false, false, false);
