-- ============================================================
-- Seed Kansas Dog Parks from DogParkList.com
-- Generated: 2026-02-18T01:31:08.541Z
-- Total parks: 42
-- Source: https://dogparklist.com/parks/
-- ============================================================

INSERT INTO parks (name, description, latitude, longitude, address, city, state, amenities, is_fenced, has_water, has_shade)
VALUES
  ('Waggin'' Tails Dog Park', 'Kansas City dog owners rate Waggin'' Tails Dog Park at 2900 Home Pl highly, with 4.6 stars from 186 visits. Dog owners looking for a solid destination will find this park delivers. The reviews indicate this is a trusted destination for dog owners in the area.', 39.2776078, -94.8994708, '2900 Home PlLeavenworth, Kansas City, KS 66048', 'Kansas City', 'KS', ARRAY[]::text[], false, false, false),
  ('Leash Free Dog Run', '53 dog owners have reviewed Leash Free Dog Run in Kansas City, averaging 4.1 stars. Open from 6am to 10pm daily, the park fits conveniently into different routines. Checking recent reviews can help dog owners decide if this park fits their needs.', 39.1688523, -94.7830641, 'Wyandotte County Lake Park RdKansas City, Kansas City, KS 66109', 'Kansas City', 'KS', ARRAY[]::text[], false, false, false),
  ('Leo Alvey Park', 'At 4850 Metropolitan Ave in Kansas City, Leo Alvey Park carries 4.1 stars from 153 dog owner reviews. Open from 6am to 9pm daily, the park is accessible for dog owners in the area. Dog owners visiting for the first time may want to read recent reviews to learn what to expect.', 39.0731767, -94.6925226, '4850 Metropolitan AveKansas City, Kansas City, KS 66106', 'Kansas City', 'KS', ARRAY[]::text[], false, false, false),
  ('Swanson''s Streamway Dog Park', 'Located at 6241 Woodland Dr in Lenexa, Swanson''s Streamway Dog Park earns strong marks from local dog owners—4.8 stars from 140 reviews. Dog owners looking for a solid destination will find this park delivers. Other dog parks in the area include Shawnee Mission Park (2.7 miles) and Buffalo Meadows Park (3.9 miles)—both great for exploring with your four-legged friend.', 39.003591, -94.8255103, '6241 Woodland DrShawnee, Lenexa, KS 66218', 'Lenexa', 'KS', ARRAY[]::text[], false, false, false),
  ('Buffalo Meadows Park', 'With 4.6 stars from 150 reviews, Buffalo Meadows Park at 9650 Lone Elm Rd has become a favorite among Lenexa dog owners. Open from 5am to 11pm daily, the park accommodates early risers and evening visitors alike. For variety, the neighborhood offers more dog parks to explore: Shawnee Mission Park (3.9 miles) and Swanson''s Streamway Dog Park (3.9 miles).', 38.9469757, -94.8345572, '9650 Lone Elm RdLenexa, Lenexa, KS 66220', 'Lenexa', 'KS', ARRAY[]::text[], false, false, false),
  ('Konza Prairie Biological Stati', 'Located at 100 Konza Prairie Ln in Manhattan, Konza Prairie Biological Stati earns strong marks from local dog owners—4.9 stars from 183 reviews. Open from 7am to 7pm daily, dog owners can plan visits around work or their pup''s energy level. For a change of scenery, Stagg Hill Park is another dog-friendly destination 4.5 miles from here.', 39.1015496, -96.6085875, '100 Konza Prairie LnManhattan, Manhattan, KS 66502', 'Manhattan', 'KS', ARRAY[]::text[], false, false, false),
  ('Warner Memorial Park', 'Manhattan dog owners rate Warner Memorial Park highly, with 4.7 stars from 159 visits. Open from 8am to 11pm daily, dog owners can plan visits around work or their pup''s energy level. Dog owners exploring the neighborhood can also bring their furry friends to Goodnow Park (0.7 miles).', 39.1836082, -96.5716694, ', Manhattan, KS', 'Manhattan', 'KS', ARRAY[]::text[], false, false, false),
  ('Fairmont Park', 'With 4.6 stars from 311 reviews, Fairmont Park at 125 Messenger Rd has become a favorite among Manhattan dog owners. Open from 6am to 11pm daily, the park offers flexibility for dog owners with varying routines. Dog owners can also take their pups to nearby Griffith Park (0.5 miles) or Goodnow Park (1.2 miles).', 39.1772998, -96.5461217, '125 Messenger RdManhattan, Manhattan, KS 66502', 'Manhattan', 'KS', ARRAY[]::text[], false, false, false),
  ('‍ Griffith Park', 'Dog owners in Manhattan have rated Griffith Park 4.4 stars across 7 reviews. Open from 6am to 11pm daily, the park gives dog owners in the neighborhood time to bring their pups. Nearby dog parks worth exploring with your pup include Fairmont Park (0.5 miles) and Warner Memorial Park (1.1 miles).', 39.1748395, -96.5548566, 'KS-18Manhattan, Manhattan, KS 66502', 'Manhattan', 'KS', ARRAY[]::text[], false, false, false),
  ('Park', 'Located at 5101 Miller Pkwy, Park in Manhattan is rated 4.4 stars by 16 dog owners. Open from 6am to 10pm daily, the park is accessible for dog owners in the area. Dog owners might also enjoy Stagg Hill Park, another dog park just 0.5 miles away.', 39.1682324, -96.6229095, '5101 Miller PkwyManhattan, Manhattan, KS 66503', 'Manhattan', 'KS', ARRAY[]::text[], false, false, false),
  ('Stagg Hill Park', 'Stagg Hill Park at 3010 Irene Cir in Manhattan has 4.4 stars from 41 dog owner reviews. Open from 6am to 10:30pm daily, the park fits conveniently into different routines. Dog owners might also enjoy Park, another dog park just 0.5 miles away.', 39.1660722, -96.61369, '3010 Irene CirManhattan, Manhattan, KS 66502', 'Manhattan', 'KS', ARRAY[]::text[], false, false, false),
  ('Northeast Community Park', 'For dog owners in Manhattan, Northeast Community Park at 680 Knox Ln has a 4.4-star rating (163 reviews). Open from 6am to 11pm daily, the park gives dog owners in the neighborhood time to bring their pups. For pups who want more adventure, Goodnow Park is a nearby dog park worth visiting (1.3 miles).', 39.2040382, -96.5461148, '680 Knox LnManhattan, Manhattan, KS 66502', 'Manhattan', 'KS', ARRAY[]::text[], false, false, false),
  ('CiCo Park', 'In Manhattan, CiCo Park has built a loyal following—4.4 stars from 554 dog owner reviews. Open from 5am to 11pm daily, the park works well for dog owners with different schedules. For variety, the neighborhood offers more dog parks to explore: Park (2.4 miles) and Stagg Hill Park (2.8 miles).', 39.2012846, -96.6379362, 'Kimball AveManhattan, Manhattan, KS 66503', 'Manhattan', 'KS', ARRAY[]::text[], false, false, false),
  ('Goodnow Park', 'Dog owners in Manhattan have rated Goodnow Park (1101 N 4th St) 4.3 stars across 75 reviews. Open from 6am to 11pm daily, dog owners in the area can work a visit into their day. Dog owners in the neighborhood can also take their furry friends to Warner Memorial Park, 0.7 miles away.', 39.1899509, -96.5614889, '1101 N 4th StManhattan, Manhattan, KS 66502', 'Manhattan', 'KS', ARRAY[]::text[], false, false, false),
  ('Shawnee Mission Park', 'At 18932 Barkley Dr in Overland Park, Shawnee Mission Park has built a loyal following—4.9 stars from 338 dog owner reviews. Dog owners looking for a solid destination will find this park delivers. Dog owners can also take their pups to nearby Swanson''s Streamway Dog Park (2.7 miles) or Buffalo Meadows Park (3.9 miles).', 38.9849368, -94.7807396, '18932 Barkley DrLenexa, Overland Park, KS 66219', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Deanna Rose Children''s Farmste', 'Dog owners have made Deanna Rose Children''s Farmste at 13800 Switzer Rd one of Overland Park''s most popular destinations—4.8 stars from 5,802 visits. Open from 9am to 5pm daily, dog owners have maximum flexibility to plan their visit. Dog owners exploring the area should also bring their pups to Lexington Park (2.6 miles) and Nottingham Downs Park (2.7 miles).', 38.8782783, -94.7005825, '13800 Switzer RdOverland Park, Overland Park, KS 66221', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Bar K', '3,256 dog owners have made Bar K (501 Berkley Pkwy) one of Overland Park''s most trusted parks (4.7 stars). Dog owners appreciate the reliable experience this park provides for their four-legged companions. Looking to mix things up? Berkley Riverfront is a nearby dog park 0.5 miles away that''s worth exploring with your pup.', 39.1146622, -94.5778417, '501 Berkley PkwyKansas City, Overland Park, KS 64120', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('‍ Franklin Park', 'With 4.7 stars from 434 reviews, Franklin Park at 8700 Roe Ave has become a favorite among Overland Park dog owners. Open from 7am to 11pm daily, the park offers flexibility for dog owners with varying routines. Nearby, Antioch Acres Park (2.8 miles) offers dog owners another great spot to explore with their pups.', 38.972853, -94.637774, '8700 Roe AvePrairie Village, Overland Park, KS 66207', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Nottingham Downs Park', 'Located at 12520 Lamar Ave in Overland Park, Nottingham Downs Park earns strong marks from local dog owners—4.7 stars from 15 reviews. Open from 5am to 10pm daily, there''s room in the day for dog owners to bring their furry friends. Dog owners exploring the neighborhood can also bring their furry friends to Lexington Park (1.2 miles).', 38.900411, -94.659232, '12520 Lamar AveOverland Park, Overland Park, KS 66209', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Kill Creek Streamway Dog Park', 'With 4.6 stars from 158 reviews, Kill Creek Streamway Dog Park at 33460 W 95th St has become a favorite among Overland Park dog owners. Open from 6am to 10pm daily, dog owners have plenty of flexibility to plan a visit. A solid track record makes this a reliable choice for dog owners.', 38.9566694, -94.9729724, '33460 W 95th StDe Soto, Overland Park, KS 66018', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Platte Landing Park', 'Located at 300 S Main St in Overland Park, Platte Landing Park earns strong marks from local dog owners—4.6 stars from 316 reviews. Open from 5:30am to 9pm daily, there''s room in the day for dog owners to bring their furry friends. Nearby, E. H. Young Riverfront Park (4.0 miles) offers dog owners another great spot to explore with their pups.', 39.1939574, -94.6837918, '300 S Main StParkville, Overland Park, KS 64152', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Thomas S. Stoll Memorial Park', 'Thomas S. Stoll Memorial Park at 12500 W 119th St is well-regarded by Overland Park dog owners, holding 4.6 stars across 845 reviews. Open from 5am to 10pm daily, the park offers flexibility for dog owners with varying routines. Nearby, Deanna Rose Children''s Farmste (2.9 miles) offers dog owners another great spot to explore with their pups.', 38.9129325, -94.7323404, '12500 W 119th StOverland Park, Overland Park, KS 66210', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Waggin'' Trail Dog Park', 'Waggin'' Trail Dog Park at 432 E 32nd Ave is a favorite among Overland Park dog owners, earning 4.6 stars from 1,077 reviews. Open from 7am to 7pm daily, the park is convenient for before work, after work, or weekend adventures. Dog owners in the area also love bringing their pups to Berkley Riverfront (2.4 miles) and E. H. Young Riverfront Park (2.4 miles).', 39.1522943, -94.5768219, '432 E 32nd AveNorth Kansas City, Overland Park, KS 64116', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Creekside Park', 'For dog owners in Overland Park, Creekside Park at 15599 Nall Ave has a 4.4-star rating (40 reviews). Open from 5am to 10pm daily, dog owners have flexibility to plan a visit with their four-legged friends. Looking to explore more? Deanna Rose Children''s Farmste is another dog-friendly park 3.6 miles from here.', 38.8458034, -94.6490665, '15599 Nall AveOverland Park, Overland Park, KS 66223', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Westbrooke Park', 'At 10702 W 88th Terrace, Westbrooke Park has 4.4 stars based on 41 reviews from Overland Park dog owners. Open from 5am to 10pm daily, dog owners can stop by when it fits their schedule. For dog owners who like to explore, Antioch Acres Park (1.8 miles) and Franklin Park (3.9 miles) are both nearby parks to try with your dog.', 38.9674348, -94.7099579, '10702 W 88th TerraceOverland Park, Overland Park, KS 66214', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Leawoof Dog Park', 'Leawoof Dog Park (4.5 stars from 423 reviews) is a popular destination for Overland Park dog owners, located at 106th & Lee Boulevard. Dog owners frequent this park for its consistent quality and welcoming atmosphere. For a change of scenery, Franklin Park is another dog-friendly destination 2.9 miles from here.', 38.9333436, -94.6199569, '106th & Lee BoulevardLeawood, Overland Park, KS 66211', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Antioch Acres Park', 'Dog owners in Overland Park have rated Antioch Acres Park (8706 W 79th St) 4.4 stars across 88 reviews. Open from 5am to 10pm daily, the park gives dog owners in the neighborhood time to bring their pups. Dog owners in the neighborhood can also take their furry friends to Westbrooke Park, 1.8 miles away.', 38.9858868, -94.6865942, '8706 W 79th StOverland Park, Overland Park, KS 66204', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Swope Dog Park', 'At 5051 E Gregory Blvd in Overland Park, Swope Dog Park has built a loyal following—4.4 stars from 563 dog owner reviews. Open from 5am to 12am daily, dog owners have plenty of flexibility to plan a visit. For variety, the neighborhood offers more dog parks to explore: Swope Park (2.8 miles) and Loose Park (4.2 miles).', 38.996687, -94.529123, '5051 E Gregory BlvdKansas City, Overland Park, KS 64132', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Penn Valley Off Leash Dog Park', 'For dog owners in the Overland Park area, Penn Valley Off Leash Dog Park offers a 4.4-star experience based on 584 reviews. Open from 5am to 12am daily, the park accommodates early risers and evening visitors alike. Looking for more places to take your pup? Frank A. Theis Park is another popular dog park just 0.0 miles away.', 39.100105, -94.5781416, ', Overland Park, KS', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Lexington Park', 'Located at 12050 Lowell Ave, Lexington Park offers Overland Park dog owners a neighborhood destination for their four-legged friends. Open from 5am to 10pm daily, dog owners have a window to spend time with their pups. Dog owners in the neighborhood can also take their furry friends to Nottingham Downs Park, 1.2 miles away.', 38.9115899, -94.6771706, '12050 Lowell AveOverland Park, Overland Park, KS 66213', 'Overland Park', 'KS', ARRAY[]::text[], false, false, false),
  ('Dog Park', 'For dog owners in the Topeka area, Dog Park (1811 NW Brickyard Rd) offers a 4.8-star experience based on 8 reviews. For dog owners in the area, this park has become a trusted spot for time with their pups. More dog-friendly parks nearby include Hills Pet Nutrition Bark Park (1.6 miles) and Big Shunga Park (3.4 miles)—perfect for pups who love adventure.', 39.0819108, -95.7259068, '1811 NW Brickyard RdTopeka, Topeka, KS 66618', 'Topeka', 'KS', ARRAY[]::text[], false, false, false),
  ('Hills Pet Nutrition Bark Park', 'With 4.5 stars from 175 reviews, Hills Pet Nutrition Bark Park at 620 SW Zoo Pkwy has become a favorite among Topeka dog owners. Dog owners frequent this park for its consistent quality and welcoming atmosphere. Nearby, Dog Park (1.6 miles) offers dog owners another great spot to explore with their pups.', 39.058184, -95.7273241, '620 SW Zoo PkwyTopeka, Topeka, KS 66606', 'Topeka', 'KS', ARRAY[]::text[], false, false, false),
  ('Big Shunga Park', 'Dog owners in Topeka have made Big Shunga Park a go-to spot, rating it 4.5 stars across 211 reviews. Open from 6am to 11pm daily, there''s plenty of opportunity for dog owners to find a time that works. For a change of scenery, Shawnee Lake Off-Leash Dog is another dog-friendly destination 0.0 miles from here.', 39.049011, -95.677556, ', Topeka, KS', 'Topeka', 'KS', ARRAY[]::text[], false, true, false),
  ('Shawnee Lake Off-Leash Dog', 'In Topeka, Shawnee Lake Off-Leash Dog carries 4.4 stars from 21 dog owner reviews. Open from 6am to 11pm daily, dog owners in the area can work a visit into their day. More dog parks in the area include Big Shunga Park (0.0 miles) and Hills Pet Nutrition Bark Park (2.7 miles)—great options for mixing up your pup''s routine.', 39.049011, -95.677556, ', Topeka, KS', 'Topeka', 'KS', ARRAY[]::text[], false, true, false),
  ('Pawnee Prairie Park', 'Pawnee Prairie Park at 2625 S Tyler Rd in Wichita is a community favorite, with 1,088 dog owners giving it 4.7 stars. Open from 4am to 12am daily, dog owners can plan visits around their pup''s favorite times to be active. Thousands of dog owners have found this to be a reliable destination for their pups.', 37.6473849, -97.4440834, '2625 S Tyler RdWichita, Wichita, KS 67209', 'Wichita', 'KS', ARRAY[]::text[], false, false, false),
  ('Haysville Dog Park', 'Located at 400 W 79th St S in Wichita, Haysville Dog Park earns strong marks from local dog owners—4.7 stars from 173 reviews. Open from 5am to 12am daily, the park accommodates early risers and evening visitors alike. Dog owners looking for a dependable spot will find this park lives up to its ratings.', 37.5493016, -97.4204013, '400 W 79th St SHaysville, Wichita, KS 67060', 'Wichita', 'KS', ARRAY[]::text[], false, false, false),
  ('Sedgwick County Park', 'Dog owners in Wichita have embraced Sedgwick County Park (6501 W 21st St) as a top destination—4.6 stars from 3,248 visits. Open from 6am to 10pm daily, dog owners have room to work around busy schedules. With this many positive experiences, dog owners can visit with confidence.', 37.723214, -97.421481, '6501 W 21st StWichita, Wichita, KS 67205', 'Wichita', 'KS', ARRAY[]::text[], false, false, false),
  ('Naftzger Park', 'Naftzger Park (4.6 stars from 330 reviews) is a popular destination for Wichita dog owners, located at 601 E Douglas Ave. Open from 6am to 12am daily, dog owners have plenty of flexibility to plan a visit. Dog owners can also take their pups to nearby Murfin Dog Park (4.2 miles) or Chapin Park (4.6 miles).', 37.686134, -97.3314752, '601 E Douglas AveWichita, Wichita, KS 67202', 'Wichita', 'KS', ARRAY[]::text[], false, false, false),
  ('Decarsky Park', 'For dog owners in the Wichita area, Decarsky Park offers a 4.6-star experience based on 108 reviews. The park has earned its reputation among dog owners in the neighborhood as a reliable choice. Local dog owners have clearly found this to be a worthwhile destination.', 37.5455735, -97.2689331, ', Wichita, KS', 'Wichita', 'KS', ARRAY[]::text[], false, false, false),
  ('W.B. Harrison Park', 'With 4.5 stars from 541 reviews, W.B. Harrison Park at 1300 S Webb Rd has become a favorite among Wichita dog owners. Open from 6am to 12am daily, the park works well for dog owners with different schedules. For a change of scenery, Dog Park is another dog-friendly destination 4.7 miles from here.', 37.6681919, -97.2260473, '1300 S Webb RdWichita, Wichita, KS 67207', 'Wichita', 'KS', ARRAY[]::text[], false, false, false),
  ('‍ Murfin Dog Park', 'Murfin Dog Park at 3313 N Hillside St holds a 4.4-star rating from 116 Wichita dog owner visits. Open from 6am to 12am daily, the park gives dog owners in the neighborhood time to bring their pups. Looking to explore more? Naftzger Park is another dog-friendly park 4.2 miles from here.', 37.7418761, -97.3010076, '3313 N Hillside StWichita, Wichita, KS 67219', 'Wichita', 'KS', ARRAY[]::text[], false, false, false),
  ('‍ Chapin Park', 'Chapin Park at 2400 E MacArthur Rd is well-regarded by Wichita dog owners, holding 4.4 stars across 771 reviews. Open from 6am to 12am daily, the park works well for dog owners with different schedules. Dog owners exploring the neighborhood can also bring their furry friends to Naftzger Park (4.6 miles).', 37.6227592, -97.3068214, '2400 E MacArthur RdWichita, Wichita, KS 67216', 'Wichita', 'KS', ARRAY[]::text[], false, false, false);
