-- ============================================================
-- Seed Louisiana Dog Parks from DogParkList.com
-- Generated: 2026-02-18T01:31:08.507Z
-- Total parks: 44
-- Source: https://dogparklist.com/parks/
-- ============================================================

INSERT INTO parks (name, description, latitude, longitude, address, city, state, amenities, is_fenced, has_water, has_shade)
VALUES
  ('Hynson Dog Park', 'Dog owners in Alexandria have rated Hynson Dog Park 4.4 stars across 175 reviews. Open from 7am to 7pm daily, dog owners have a window to spend time with their pups. Dog owners can find more details about this park in the reviews from other visitors.', 31.2882116, -92.4534378, 'Gilbert StAlexandria, ‍ Alexandria, LA 71301', '‍ Alexandria', 'LA', ARRAY[]::text[], false, false, false),
  ('City-Brooks Community Park', 'With 4.6 stars across 1,079 reviews, City-Brooks Community Park at 1515 Dalrymple Dr has clearly won over Baton Rouge dog owners. Open from 7am to 6pm daily, the park accommodates a variety of dog owner schedules and routines. Nearby, Raising Cane''s Dog Park (0.3 miles) is another dog park favorite where you can take your four-legged friend.', 30.4312312, -91.167521, '1515 Dalrymple DrBaton Rouge, Baton Rouge, LA 70806', 'Baton Rouge', 'LA', ARRAY[]::text[], false, false, false),
  ('Dog Park', 'Dog Park (4.6 stars from 536 reviews) is a popular destination for Baton Rouge dog owners, located at 12400 Burbank Dr. Open from 6am to 7pm, Tuesday through Sunday, there''s plenty of opportunity for dog owners to find a time that works. Looking for more places to take your pup? City-Brooks Community Park is another popular dog park just 3.1 miles away.', 30.3868378, -91.1557645, '12400 Burbank DrBaton Rouge, Baton Rouge, LA 70810', 'Baton Rouge', 'LA', ARRAY[]::text[], false, false, false),
  ('Raising Canes Dog Park', 'With 4.6 stars from 182 reviews, Raising Canes Dog Park at 13900 S Harrells Ferry Rd has become a favorite among Baton Rouge dog owners. Open from 8am to 8pm daily, the park offers flexibility for dog owners with varying routines. Dog owners looking for a dependable spot will find this park lives up to its ratings.', 30.4253091, -91.0071143, '13900 S Harrells Ferry RdBaton Rouge, Baton Rouge, LA 70816', 'Baton Rouge', 'LA', ARRAY[]::text[], false, false, false),
  ('West Baton Rouge Dog Park', 'West Baton Rouge Dog Park (4.6 stars from 25 reviews) is a popular destination for Baton Rouge dog owners, located at 610 Rosedale Rd. The steady stream of dog owner visits speaks to the park''s appeal. Dog owners can also take their pups to nearby Raising Cane''s Dog Park (3.0 miles) or City-Brooks Community Park (3.3 miles).', 30.4635248, -91.2076891, '610 Rosedale RdPort Allen, Baton Rouge, LA 70767', 'Baton Rouge', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ Raising Cane''s Dog Park', 'For dog owners in the Baton Rouge area, Raising Cane''s Dog Park (1442 City Park Ave) offers a 4.5-star experience based on 552 reviews. Open from 7am to 7pm, every day except Tuesday and Thursday, the park accommodates early risers and evening visitors alike. For variety, the neighborhood offers more dog parks to explore: City-Brooks Community Park (0.3 miles) and West Baton Rouge Dog Park (3.0 miles).', 30.4346765, -91.1692752, '1442 City Park AveBaton Rouge, Baton Rouge, LA 70808', 'Baton Rouge', 'LA', ARRAY[]::text[], false, false, false),
  ('Field of Dreams', 'Dog owners in Bossier City have made Field of Dreams at 4714 Hazel Jones Rd a go-to spot, rating it 4.8 stars across 321 reviews. Open from 6am to 8pm daily, there''s plenty of opportunity for dog owners to find a time that works. For variety, the neighborhood offers more dog parks to explore: Hooter Park (3.0 miles) and Mike Wood Memorial Park (4.4 miles).', 32.5469088, -93.6734758, '4714 Hazel Jones RdBossier City, Bossier City, LA 71111', 'Bossier City', 'LA', ARRAY[]::text[], false, false, false),
  ('Red River National Wildlife', 'With 4.7 stars from 838 reviews, Red River National Wildlife at 150 Eagle Bend Point has become a favorite among Bossier City dog owners. Open from 8am to 4pm, Monday through Saturday, the park accommodates early risers and evening visitors alike. Dog owners exploring the neighborhood can also bring their furry friends to Mike Wood Memorial Park (2.6 miles).', 32.4474431, -93.6723251, '150 Eagle Bend PointBossier City, Bossier City, LA 71112', 'Bossier City', 'LA', ARRAY[]::text[], false, false, false),
  ('Hooter Park', 'Hooter Park (5.0 stars from 6 reviews) is a popular destination for Bossier City dog owners, located at 1519 Hooter St. Dog owners frequent this park for its consistent quality and welcoming atmosphere. Dog owners can also take their pups to nearby Mike Wood Memorial Park (2.1 miles) or East Kings Highway Park (2.8 miles).', 32.5061995, -93.6887699, '1519 Hooter StBossier City, Bossier City, LA 71112', 'Bossier City', 'LA', ARRAY[]::text[], false, false, false),
  ('Veterans Memorial Park', 'With 4.6 stars from 223 reviews, Veterans Memorial Park has become a favorite among Bossier City dog owners. For dog owners in the area, this park has become a trusted spot for time with their pups. Looking for more places to take your pup? Stoner Avenue Recreation Area is another popular dog park just 0.0 miles away.', 32.5135356, -93.7477839, ', Bossier City, LA', 'Bossier City', 'LA', ARRAY[]::text[], false, false, false),
  ('Stoner Avenue Recreation Area', 'Stoner Avenue Recreation Area is well-regarded by Bossier City dog owners, holding 4.5 stars across 6 reviews. Local dog owners appreciate what this park offers their four-legged friends. Dog owners can also take their pups to nearby Veterans Memorial Park (0.0 miles) or Shreveport Dog Park (0.9 miles).', 32.5135356, -93.7477839, ', Bossier City, LA', 'Bossier City', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ Mike Wood Memorial Park', 'Bossier City dog owners rate Mike Wood Memorial Park at 2200 Dennis St highly, with 4.5 stars from 410 visits. Dog owners in the area consistently choose this park as a go-to destination for their pups. More dog-friendly parks nearby include Hooter Park (2.1 miles) and Red River National Wildlife (2.6 miles)—perfect for pups who love adventure.', 32.4842592, -93.6631662, '2200 Dennis StBossier City, Bossier City, LA 71112', 'Bossier City', 'LA', ARRAY[]::text[], false, false, false),
  ('Southern Hills Park', 'Southern Hills Park at 1002 W Bert Kouns Industrial Loop is well-regarded by Bossier City dog owners, holding 4.4 stars across 597 reviews. The steady stream of dog owner visits speaks to the park''s appeal. The consistent ratings suggest dog owners know what to expect here.', 32.4021495, -93.7851043, '1002 W Bert Kouns Industrial LoopShreveport, Bossier City, LA 71118', 'Bossier City', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ East Kings Highway Park', 'East Kings Highway Park at 1200 E Kings Hwy is well-regarded by Bossier City dog owners, holding 4.4 stars across 755 reviews. Open from 6am to 10pm daily, dog owners can easily fit a visit into busy schedules. More dog-friendly parks nearby include Betty Virginia Park (2.3 miles) and Hooter Park (2.8 miles)—perfect for pups who love adventure.', 32.47103, -93.711569, '1200 E Kings HwyShreveport, Bossier City, LA 71105', 'Bossier City', 'LA', ARRAY[]::text[], false, false, false),
  ('Moncus Park', 'With 4.7 stars from 583 reviews, Moncus Park at 2913 Johnston St has become a favorite among Lafayette dog owners. Open from 5am to 10pm daily, the park offers flexibility for dog owners with varying routines. Dog owners can also take their pups to nearby Parc de Lafayette (1.9 miles) or The Saloom Family Community (2.0 miles).', 30.2055904, -92.0409975, '2913 Johnston StLafayette, Lafayette, LA 70503', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('Acadiana Park', 'Acadiana Park (4.7 stars from 271 reviews) is a popular destination for Lafayette dog owners, located at 1205 E Alexander St. Local dog owners appreciate what this park offers their four-legged friends. For variety, the neighborhood offers more dog parks to explore: Mouton Park (1.1 miles) and Graham Brown Memorial Park (1.5 miles).', 30.2534678, -91.9860147, '1205 E Alexander StLafayette, Lafayette, LA 70501', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('Mouton Park', 'Lafayette dog owners rate Mouton Park at 803 Center St highly, with 4.6 stars from 28 visits. Local dog owners appreciate what this park offers their four-legged friends. Looking for more places to take your pup? Veteran''s Park is another popular dog park just 1.1 miles away.', 30.2396774, -91.9947382, '803 Center StLafayette, Lafayette, LA 70501', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('Parc de Lafayette', 'At 539 Jefferson St in Lafayette, Parc de Lafayette has built a loyal following—4.5 stars from 34 dog owner reviews. The park serves dog owners well, providing a destination the community values. For variety, the neighborhood offers more dog parks to explore: The Saloom Family Community (0.1 miles) and Chargois Park (0.1 miles).', 30.2251042, -92.0186898, '539 Jefferson StLafayette, Lafayette, LA 70501', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('Skye''s Dream Dog Park', '13 dog owners have reviewed Skye''s Dream Dog Park in Lafayette, averaging 4.3 stars. Dog owners in the area appreciate having a local spot to bring their pups. Reviews from other dog owners provide perspective on what to expect at this park.', 30.2735323, -91.8992837, ', Lafayette, LA', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('Veterans Park', 'Located at 200 Feu Follet Rd, Veterans Park in Lafayette is rated 4.4 stars by 248 dog owners. For dog owners in the neighborhood, this park offers a place to take their pups. Dog owners might also enjoy Beaullieu Park, another dog park just 1.7 miles away.', 30.18198, -92.015093, '200 Feu Follet RdLafayette, Lafayette, LA 70508', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('Graham Brown Memorial Park', 'For dog owners in Lafayette, Graham Brown Memorial Park at 1234 E Pont Des Mouton Rd has a 4.4-star rating (284 reviews). Open from 7am to 8pm daily, local dog owners have time to explore with their furry companions. Dog owners looking for variety can also visit Acadiana Park (1.5 miles) or Mouton Park (2.3 miles) with their four-legged friends.', 30.2724479, -91.9967683, '1234 E Pont Des Mouton RdLafayette, Lafayette, LA 70507', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ Veteran''s Park', 'For dog owners in Lafayette, Veteran''s Park at 100 Moss St has a 4.2-star rating (19 reviews). The neighborhood benefits from having this park as an option for dog owners and their pups. Looking to explore more? The Saloom Family Community is another dog-friendly park 0.6 miles from here.', 30.230188, -92.009009, '100 Moss StLafayette, Lafayette, LA 70501', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('Beaullieu Park', 'For dog owners in Lafayette, Beaullieu Park at 411 W Bluebird Dr has a 4.3-star rating (276 reviews). Dog owners in the area appreciate having a local spot to bring their pups. For dog owners who like to explore, Veterans Park (1.7 miles) and Moncus Park (3.3 miles) are both nearby parks to try with your dog.', 30.1598961, -92.0271178, '411 W Bluebird DrLafayette, Lafayette, LA 70508', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('The Saloom Family Community', 'The Saloom Family Community serves dog owners in the Lafayette neighborhood looking for a place to visit with their pups. The park gives neighborhood dog owners a destination for outings with their four-legged friends. More dog parks in the area include Chargois Park (0.0 miles) and Parc de Lafayette (0.1 miles)—great options for mixing up your pup''s routine.', 30.2262187, -92.0178202, ', Lafayette, LA', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('Chargois Park', 'Chargois Park holds a 4.2-star rating from 123 Lafayette dog owner visits. The park serves as a gathering spot for dog owners and their four-legged friends in the area. For pups who want more adventure, The Saloom Family Community is a nearby dog park worth visiting (0.0 miles).', 30.2262187, -92.0178202, ', Lafayette, LA', 'Lafayette', 'LA', ARRAY[]::text[], false, false, false),
  ('Bark Du Lac Dog Park', 'Dog owners in Lake Charles have rated Bark Du Lac Dog Park (100-198 W Pine St) 4.3 stars across 191 reviews. Open from 9am to 9pm daily, dog owners have a window to spend time with their pups. For dog owners considering a visit, the reviews offer firsthand accounts from other visitors.', 30.2329221, -93.2187372, '100-198 W Pine StLake Charles, ‍ Lake Charles, LA 70601', '‍ Lake Charles', 'LA', ARRAY[]::text[], false, true, false),
  ('New Orleans City Park', 'At 1 Palm Dr in New Orleans, New Orleans City Park draws dog owners from across the area—4.8 stars from 19,349 reviews. Open from 5am to 10pm daily, dog owners can find the perfect time for their furry friend. The neighborhood offers dog owners more places to bring their pups: Hardin Park (0.8 miles) and The Dog House (1.1 miles).', 29.9759983, -90.0782127, '1 Palm DrNew Orleans, New Orleans, LA 70124', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ Lafreniere Park', 'Lafreniere Park at 3000 Downs Blvd in New Orleans is a community favorite, with 4,452 dog owners giving it 4.7 stars. Dog owners appreciate the reliable experience this park provides for their four-legged companions. For variety, many dog owners also bring their furry friends to Rio Vista Dog Park (4.0 miles)—another great dog park in the area.', 29.9988019, -90.2087903, '3000 Downs BlvdMetairie, New Orleans, LA 70003', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ Audubon Park', 'Audubon Park at 6500 Magazine St in New Orleans has earned its reputation with 4.7 stars from 8,318 dog owner reviews. Open from 5am to 10pm daily, dog owners have maximum flexibility to plan their visit. The neighborhood offers dog owners more places to bring their pups: Carver Playground (0.7 miles) and Wisner Playground (1.2 miles).', 29.924361, -90.127358, '6500 Magazine StNew Orleans, New Orleans, LA 70118', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ The Dog House', 'For dog owners in the New Orleans area, The Dog House (2736 Banks St) offers a 4.6-star experience based on 40 reviews. The park has earned its reputation among dog owners in the neighborhood as a reliable choice. Nearby, New Orleans City Park (1.1 miles) offers dog owners another great spot to explore with their pups.', 29.9630566, -90.090139, '2736 Banks StNew Orleans, New Orleans, LA 70119', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Kenner City Park', 'New Orleans dog owners rate Kenner City Park at 3800 Loyola Dr highly, with 4.6 stars from 58 visits. Dog owners in the area consistently choose this park as a go-to destination for their pups. For a change of scenery, Lafreniere Park is another dog-friendly destination 4.3 miles from here.', 30.0338731, -90.2676194, '3800 Loyola DrKenner, New Orleans, LA 70065', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Fleur De Lis Park', 'For dog owners in the New Orleans area, Fleur De Lis Park (6701 Fleur De Lis Dr) offers a 4.6-star experience based on 76 reviews. Open from 6am to 10pm daily, there''s room in the day for dog owners to bring their furry friends. More dog-friendly parks nearby include Pontiff Park (2.4 miles) and New Orleans City Park (3.6 miles)—perfect for pups who love adventure.', 30.0143142, -90.1182857, '6701 Fleur De Lis DrNew Orleans, New Orleans, LA 70124', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Clouet Gardens', 'Clouet Gardens (4.6 stars from 103 reviews) is a popular destination for New Orleans dog owners, located at 710 Clouet St. Open from 6am to 9:30pm daily, the park offers flexibility for dog owners with varying routines. Dog owners exploring the neighborhood can also bring their furry friends to Mickey Markey Park (0.2 miles).', 29.9637033, -90.0454939, '710 Clouet StNew Orleans, New Orleans, LA 70117', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Woldenberg Park', 'Dog owners have made Woldenberg Park at 1 Canal St one of New Orleans''s most popular destinations—4.6 stars from 5,745 visits. Tens of thousands of dog owners have discovered what makes this park special. Dog owners in the area also frequent Cabrini Playground (0.9 miles)—another top dog park worth visiting with your pup.', 29.9508819, -90.0632066, '1 Canal StNew Orleans, New Orleans, LA 70130', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Parc des Familles Dog Park', 'For dog owners in the New Orleans area, Parc des Familles Dog Park (6101 Lafitte Pkwy) offers a 4.5-star experience based on 49 reviews. Open from 7am to 6pm daily, dog owners can plan visits around work or their pup''s energy level. Dog owners looking for a dependable spot will find this park lives up to its ratings.', 29.8018526, -90.0914731, '6101 Lafitte PkwyMarrero, New Orleans, LA 70072', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ McDonough Zachery Park', 'Located at 1500 Toledano St, McDonough Zachery Park in New Orleans is rated 4.3 stars by 15 dog owners. The neighborhood benefits from having this park as an option for dog owners and their pups. For dog owners who like to explore, Coliseum Square Park (1.1 miles) and Wisner Dog Park (1.2 miles) are both nearby parks to try with your dog.', 29.927426, -90.089694, '1500 Toledano StNew Orleans, New Orleans, LA 70115', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ Wisner Playground', 'Located at 4877 Laurel St in New Orleans, Wisner Playground earns strong marks from local dog owners—4.5 stars from 66 reviews. Open from 6am to 9pm daily, dog owners can plan visits around work or their pup''s energy level. Other dog parks in the area include Wisner Dog Park (0.0 miles) and Audubon Park (1.2 miles)—both great for exploring with your four-legged friend.', 29.9183368, -90.1079842, '4877 Laurel StNew Orleans, New Orleans, LA 70115', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Carver Playground', 'At 7410 Prytania St in New Orleans, Carver Playground carries 4.4 stars from 29 dog owner reviews. Open from 6am to 9pm daily, dog owners have a window to spend time with their pups. Dog owners might also enjoy Audubon Park, another dog park just 0.7 miles away.', 29.9334361, -90.1333282, '7410 Prytania StNew Orleans, New Orleans, LA 70118', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Camellia City Bark Park', 'For dog owners in the New Orleans area, Camellia City Bark Park (901 Howze Beach Rd) offers a 4.5-star experience based on 142 reviews. Open from 7am to 5pm daily, dog owners have plenty of flexibility to plan a visit. Local dog owners have clearly found this to be a worthwhile destination.', 30.2466145, -89.7698004, '901 Howze Beach RdSlidell, New Orleans, LA 70458', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Coliseum Square Park', 'Located at 1708 Coliseum St in New Orleans, Coliseum Square Park earns strong marks from local dog owners—4.5 stars from 583 reviews. Open from 6am to 10:30pm daily, there''s plenty of opportunity for dog owners to find a time that works. Nearby, McDonough Zachery Park (1.1 miles) offers dog owners another great spot to explore with their pups.', 29.936014, -90.0741407, '1708 Coliseum StNew Orleans, New Orleans, LA 70130', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Mickey Markey Park', '90 dog owners have reviewed Mickey Markey Park at 3301 Royal St in New Orleans, averaging 4.4 stars. Dog owners in the area appreciate having a local spot to bring their pups. Dog owners might also enjoy Clouet Gardens, another dog park just 0.2 miles away.', 29.962938, -90.042693, '3301 Royal StNew Orleans, New Orleans, LA 70117', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('Rio Vista Dog Park', 'Rio Vista Dog Park serves dog owners in the New Orleans neighborhood looking for a place to visit with their pups. The neighborhood benefits from having this park as an option for dog owners and their pups. For dog owners who like to explore, Pontiff Park (1.5 miles) and Harrell Park (1.7 miles) are both nearby parks to try with your dog.', 29.9665206, -90.1529006, ', New Orleans, LA', 'New Orleans', 'LA', ARRAY[]::text[], false, false, false),
  ('‍ Betty Virginia Park', 'With 4.6 stars across 1,065 reviews, Betty Virginia Park at 3901 Fairfield Ave has clearly won over Shreveport dog owners. Open from 5am to 10pm daily, the park is convenient for before work, after work, or weekend adventures. Nearby, Shreveport Dog Park (2.2 miles) is another dog park favorite where you can take your four-legged friend.', 32.469088, -93.75024, '3901 Fairfield AveShreveport, Shreveport, LA 71106', 'Shreveport', 'LA', ARRAY[]::text[], false, false, false),
  ('Shreveport Dog Park', 'At 857 E Stoner Ave, Shreveport Dog Park has 4.4 stars based on 396 reviews from Shreveport dog owners. The neighborhood benefits from having this park as an option for dog owners and their pups. Dog owners looking for variety can also visit Veterans Memorial Park (0.9 miles) or Stoner Avenue Recreation Area (0.9 miles) with their four-legged friends.', 32.499971, -93.7452041, '857 E Stoner AveShreveport, Shreveport, LA 71101', 'Shreveport', 'LA', ARRAY[]::text[], false, false, false);
