-- ============================================================
-- Seed Oklahoma Dog Parks from DogParkList.com
-- Generated: 2026-02-18T01:31:08.577Z
-- Total parks: 33
-- Source: https://dogparklist.com/parks/
-- ============================================================

INSERT INTO parks (name, description, latitude, longitude, address, city, state, amenities, is_fenced, has_water, has_shade)
VALUES
  ('Nienhuis Park', 'Located at 3201 N 9th St in Broken Arrow, Nienhuis Park earns strong marks from local dog owners—4.6 stars from 82 reviews. Open from 7am to 11pm daily, dog owners have plenty of flexibility to plan a visit. Looking for more places to take your pup? Preserve Park is another popular dog park just 2.0 miles away.', 36.0845747, -95.7784101, '3201 N 9th StBroken Arrow, Broken Arrow, OK 74012', 'Broken Arrow', 'OK', ARRAY[]::text[], false, false, false),
  ('‍ Preserve Park', 'Preserve Park (4.6 stars from 25 reviews) is a popular destination for Broken Arrow dog owners, located at 3000 N 37th St. Open from 7am to 11pm daily, the park works well for dog owners with different schedules. More dog-friendly parks nearby include Nienhuis Park (2.0 miles) and Oak Creek Park (2.4 miles)—perfect for pups who love adventure.', 36.0756693, -95.7439405, '3000 N 37th StBroken Arrow, Broken Arrow, OK 74014', 'Broken Arrow', 'OK', ARRAY[]::text[], false, false, false),
  ('Oak Creek Park', 'Oak Creek Park (4.5 stars from 14 reviews) is a popular destination for Broken Arrow dog owners, located at 2725 E Louisville St. Open from 7am to 11pm daily, the park accommodates early risers and evening visitors alike. Dog owners exploring the neighborhood can also bring their furry friends to Washington Lane Neighborhood (1.4 miles).', 36.0424614, -95.7568265, '2725 E Louisville StBroken Arrow, Broken Arrow, OK 74014', 'Broken Arrow', 'OK', ARRAY[]::text[], false, false, false),
  ('Aspen Creek Park', 'For dog owners in Broken Arrow, Aspen Creek Park at 320 S Oak Ave has a 4.4-star rating (114 reviews). Open from 7am to 11pm daily, dog owners have flexibility to plan a visit with their four-legged friends. Nearby dog parks worth exploring with your pup include Washington Lane Neighborhood (2.5 miles) and Oak Creek Park (2.9 miles).', 36.0490592, -95.808817, '320 S Oak AveBroken Arrow, Broken Arrow, OK 74012', 'Broken Arrow', 'OK', ARRAY[]::text[], false, false, false),
  ('Langenheim Park', 'Langenheim Park at 4701 S Harvard Ave in Broken Arrow has 4.2 stars from 203 dog owner reviews. Open from 7am to 8pm daily, the park fits conveniently into different routines. Dog owners looking for variety can also visit Route 66 Dog Park (4.3 miles) or Veterans Park (4.6 miles) with their four-legged friends.', 36.095115, -95.940099, '4701 S Harvard AveTulsa, Broken Arrow, OK 74135', 'Broken Arrow', 'OK', ARRAY[]::text[], false, false, false),
  ('‍ Washington Lane Neighborhood', 'Broken Arrow dog owners have access to Washington Lane Neighborhood at 2502 South 15th Pl E for outings with their four-legged friends. Open from 5am to 11pm daily, dog owners have flexibility to plan a visit with their four-legged friends. For dog owners who like to explore, Oak Creek Park (1.4 miles) and Aspen Creek Park (2.5 miles) are both nearby parks to try with your dog.', 36.0277194, -95.7733838, '2502 South 15th Pl EBroken Arrow, Broken Arrow, OK 74012', 'Broken Arrow', 'OK', ARRAY[]::text[], false, false, false),
  ('‍ Meadowlake Park', 'For dog owners in the Enid area, Meadowlake Park offers a 4.4-star experience based on 1,000 reviews. The steady stream of dog owner visits speaks to the park''s appeal. Other dog parks in the area include AMBUCS Park (3.3 miles) and Crosslin Park (4.2 miles)—both great for exploring with your four-legged friend.', 36.3763653, -97.9414011, 'W Rupe AveEnid, Enid, OK 73703', 'Enid', 'OK', ARRAY[]::text[], false, true, false),
  ('AMBUCS Park', '153 dog owners have reviewed AMBUCS Park in Enid, averaging 4.4 stars. For dog owners in the neighborhood, this park offers a place to take their pups. More dog parks in the area include Crosslin Park (2.0 miles) and Berry Park (2.5 miles)—great options for mixing up your pup''s routine.', 36.3993617, -97.8901527, 'N Van Buren StEnid, Enid, OK 73703', 'Enid', 'OK', ARRAY[]::text[], false, false, false),
  ('Crosslin Park', 'For dog owners in Enid, Crosslin Park at 1520 W Oxford Ave has a 4.3-star rating (369 reviews). Dog owners looking for a local destination will find this park accessible. Nearby dog parks worth exploring with your pup include Berry Park (1.1 miles) and AMBUCS Park (2.0 miles).', 36.427142, -97.8992751, '1520 W Oxford AveEnid, Enid, OK 73703', 'Enid', 'OK', ARRAY[]::text[], false, false, false),
  ('‍ Berry Park', 'For dog owners near 4100 N Washington St in Enid, Berry Park provides a convenient spot to take their dogs. Dog owners in the area appreciate having a local spot to bring their pups. For dog owners who like to explore, Crosslin Park (1.1 miles) and AMBUCS Park (2.5 miles) are both nearby parks to try with your dog.', 36.4353149, -97.8817587, '4100 N Washington StEnid, Enid, OK 73701', 'Enid', 'OK', ARRAY[]::text[], false, false, false),
  ('Elmer Thomas Park', 'With 4.6 stars across 2,211 reviews, Elmer Thomas Park at 501 NW Ferris Ave has clearly won over Lawton dog owners. Open from 6am to 11pm daily, the park is convenient for before work, after work, or weekend adventures. Looking to mix things up? The Vito Baxter Puppy Promenad is a nearby dog park 2.7 miles away that''s worth exploring with your pup.', 34.616138, -98.395366, '501 NW Ferris AveLawton, Lawton, OK 73507', 'Lawton', 'OK', ARRAY[]::text[], false, false, false),
  ('The Vito Baxter Puppy Promenad', 'The Vito Baxter Puppy Promenad at 3200 SW Lee Blvd holds a 4.1-star rating from 107 Lawton dog owner visits. Open from 9am to 11pm daily, dog owners can stop by when it fits their schedule. Dog owners in the neighborhood can also take their furry friends to Elmer Thomas Park, 2.7 miles away.', 34.594222, -98.434457, '3200 SW Lee BlvdLawton, Lawton, OK 73505', 'Lawton', 'OK', ARRAY[]::text[], false, false, false),
  ('The Water Bark LLC', 'With 4.9 stars from 76 reviews, The Water Bark LLC at 3800 N Cromwell Ave has become a favorite among Oklahoma City dog owners. Dog owners looking for a solid destination will find this park delivers. Looking for more places to take your pup? Denniston Park is another popular dog park just 1.1 miles away.', 35.5089377, -97.5777575, '3800 N Cromwell AveOklahoma City, Oklahoma City, OK 73112', 'Oklahoma City', 'OK', ARRAY['water_access']::text[], false, true, false),
  ('Bar K', 'With 4.8 stars from 587 reviews, Bar K at 901 SE 5th St has become a favorite among Oklahoma City dog owners. Dog owners looking for a solid destination will find this park delivers. For variety, the neighborhood offers more dog parks to explore: Regatta Park (0.5 miles) and Bricktown River Walk Park (0.6 miles).', 35.4607013, -97.496037, '901 SE 5th StOklahoma City, Oklahoma City, OK 73129', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Scissortail Park', 'Located at 220 SW 14th St in Oklahoma City, Scissortail Park earns strong marks from local dog owners—4.8 stars from 140 reviews. Open from 6am to 11pm daily, dog owners can easily fit a visit into busy schedules. For a change of scenery, Wheeler Park is another dog-friendly destination 0.4 miles from here.', 35.4509291, -97.5166502, '220 SW 14th StOklahoma City, Oklahoma City, OK 73109', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Myriad Botanical Gardens', 'With 10,044 reviews and a 4.7-star rating, Myriad Botanical Gardens (301 W Reno Ave) has become a landmark for Oklahoma City dog owners. Dog owners know this is a destination that consistently delivers for their pups. Dog owners in the area also frequent Robert S. Kerr Park (0.4 miles)—another top dog park worth visiting with your pup.', 35.464354, -97.51803, '301 W Reno AveOklahoma City, Oklahoma City, OK 73102', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Bricktown River Walk Park', '3,683 dog owners have made Bricktown River Walk Park (400 E Reno Ave) one of Oklahoma City''s most trusted parks (4.7 stars). Open from 4:30am to 11pm daily, the park accommodates a variety of dog owner schedules and routines. Nearby, Regatta Park (0.5 miles) is another dog park favorite where you can take your four-legged friend.', 35.4634166, -97.5053261, '400 E Reno AveOklahoma City, Oklahoma City, OK 73104', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Martin Park', 'For Oklahoma City dog owners, Martin Park at 5000 W Memorial Rd has become a reliable favorite—4.7 stars from 2,465 reviews. Open from 7am to 5pm, every day except Monday and Tuesday, there''s always time for dog owners to bring their pup for some quality time. Nearby, Pat Murphy Park (1.9 miles) is another dog park favorite where you can take your four-legged friend.', 35.609074, -97.6108265, '5000 W Memorial RdOklahoma City, Oklahoma City, OK 73142', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('E.C. Hafer Park', 'With 4.7 stars across 1,633 reviews, E.C. Hafer Park at 1034 S Bryant Ave has clearly won over Oklahoma City dog owners. Open from 6am to 11pm daily, it''s easy for dog owners to stop by whenever works best. Nearby, Edmond Dog Park (1.7 miles) is another dog park favorite where you can take your four-legged friend.', 35.6441072, -97.4603357, '1034 S Bryant AveEdmond, Oklahoma City, OK 73034', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Wayman''s Park', 'Wayman''s Park at 1901 N Drexel Blvd is well-regarded by Oklahoma City dog owners, holding 4.6 stars across 36 reviews. The steady stream of dog owner visits speaks to the park''s appeal. More dog-friendly parks nearby include Denniston Park (0.5 miles) and Swatek Park (1.3 miles)—perfect for pups who love adventure.', 35.488055, -97.5703, '1901 N Drexel BlvdOklahoma City, Oklahoma City, OK 73107', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Robert S. Kerr Park', 'Dog owners in Oklahoma City have made Robert S. Kerr Park at 102 Robert S Kerr Ave a go-to spot, rating it 4.6 stars across 86 reviews. The steady stream of dog owner visits speaks to the park''s appeal. Looking for more places to take your pup? Scissortail Park is another popular dog park just 0.3 miles away.', 35.4697278, -97.5145813, '102 Robert S Kerr AveOklahoma City, Oklahoma City, OK 73102', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Ruby Grant Park', 'Dog owners in Oklahoma City have made Ruby Grant Park at 4396 N Interstate Dr a go-to spot, rating it 4.6 stars across 118 reviews. Dog owners frequent this park for its consistent quality and welcoming atmosphere. Nearby, Norman Community Dog Park (4.4 miles) offers dog owners another great spot to explore with their pups.', 35.2713549, -97.4860262, '4396 N Interstate DrNorman, Oklahoma City, OK 73072', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Wheeler Park', 'Wheeler Park (4.6 stars from 140 reviews) is a popular destination for Oklahoma City dog owners. The park has earned its reputation among dog owners in the neighborhood as a reliable choice. Dog owners exploring the neighborhood can also bring their furry friends to Scissortail Park (0.3 miles).', 35.4545434, -97.5228913, 'Wheeler Park DrOklahoma City, Oklahoma City, OK 73109', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Perle Mesta Park', 'Dog owners in Oklahoma City have made Perle Mesta Park at 1900 N Shartel Ave a go-to spot, rating it 4.6 stars across 251 reviews. Open from 5am to 11pm daily, dog owners have plenty of flexibility to plan a visit. Other dog parks in the area include Midtown Mutts Dog Park (0.6 miles) and Goodholm Park (0.8 miles)—both great for exploring with your four-legged friend.', 35.488197, -97.525752, '1900 N Shartel AveOklahoma City, Oklahoma City, OK 73103', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('‍ Regatta Park', 'At 701 S Lincoln Blvd in Oklahoma City, Regatta Park has built a loyal following—4.6 stars from 386 dog owner reviews. Open from 11:30am to 5:30pm, every day except Monday and Tuesday, the park works well for dog owners with different schedules. More dog-friendly parks nearby include Bricktown River Walk Park (0.5 miles) and Bar K (0.5 miles)—perfect for pups who love adventure.', 35.455713, -97.5035989, '701 S Lincoln BlvdOklahoma City, Oklahoma City, OK 73129', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Pat Murphy Park', 'Located at 4551 W Hefner Rd in Oklahoma City, Pat Murphy Park earns strong marks from local dog owners—4.6 stars from 387 reviews. Open from 8am to 11pm daily, there''s room in the day for dog owners to bring their furry friends. More dog-friendly parks nearby include Martin Park (1.9 miles) and Berta Faye Rex Quail Creek (2.0 miles)—perfect for pups who love adventure.', 35.5821538, -97.6046818, '4551 W Hefner RdOklahoma City, Oklahoma City, OK 73162', 'Oklahoma City', 'OK', ARRAY[]::text[], false, false, false),
  ('Hunter Park', 'At 5804 E 91st St in Tulsa, Hunter Park stands out with 4.7 stars from 1,628 happy dog owners. Open from 5am to 9pm daily, dog owners can plan visits around their pup''s favorite times to be active. For more dog park adventures, explore Rose West Dog Park (3.8 miles) or Bark West Dog Park (4.0 miles) with your furry companion.', 36.0319756, -95.911732, '5804 E 91st StTulsa, Tulsa, OK 74137', 'Tulsa', 'OK', ARRAY[]::text[], false, false, false),
  ('Bark West Dog Park', 'For dog owners in the Tulsa area, Bark West Dog Park (990 W 101st St) offers a 4.7-star experience based on 141 reviews. Open from 6am to 7pm daily, dog owners can plan visits around work or their pup''s energy level. Looking for more places to take your pup? Hunter Park is another popular dog park just 4.0 miles away.', 36.01734, -95.9817362, '990 W 101st StJenks, Tulsa, OK 74037', 'Tulsa', 'OK', ARRAY[]::text[], false, false, false),
  ('Rose West Dog Park', 'Rose West Dog Park (4.6 stars from 400 reviews) is a popular destination for Tulsa dog owners, located at 4751 W New Orleans St. Open from 5am to 10pm, every day except Wednesday, dog owners can easily fit a visit into busy schedules. For variety, the neighborhood offers more dog parks to explore: Aspen Creek Park (3.1 miles) and Hunter Park (3.8 miles).', 36.016237, -95.8470626, '4751 W New Orleans StBroken Arrow, Tulsa, OK 74011', 'Tulsa', 'OK', ARRAY[]::text[], false, false, false),
  ('Waggin Trail Dog Park', 'At 8200 N 91st E Ave in Tulsa, Waggin Trail Dog Park has built a loyal following—4.5 stars from 207 dog owner reviews. For dog owners in the area, this park has become a trusted spot for time with their pups. The positive feedback from local dog owners speaks to the park''s consistent quality.', 36.2724302, -95.8698131, '8200 N 91st E AveOwasso, Tulsa, OK 74055', 'Tulsa', 'OK', ARRAY[]::text[], false, false, false),
  ('Veterans Park', 'Dog owners in Tulsa have made Veterans Park at 1028 E 6th St a go-to spot, rating it 4.5 stars across 815 reviews. Open from 5am to 11pm daily, the park offers flexibility for dog owners with varying routines. For variety, the neighborhood offers more dog parks to explore: Route 66 Dog Park (0.4 miles) and Joe Station Dog Park (2.1 miles).', 36.1528481, -95.9793598, '1028 E 6th StTulsa, Tulsa, OK 74120', 'Tulsa', 'OK', ARRAY[]::text[], false, false, false),
  ('‍ Joe Station Dog Park', 'Located at 2279 Charles Page Blvd in Tulsa, Joe Station Dog Park earns strong marks from local dog owners—4.4 stars from 593 reviews. Dog owners in the area consistently choose this park as a go-to destination for their pups. Looking for more places to take your pup? Route 66 Dog Park is another popular dog park just 2.0 miles away.', 36.1513988, -96.0172148, '2279 Charles Page BlvdTulsa, Tulsa, OK 74127', 'Tulsa', 'OK', ARRAY[]::text[], false, false, false),
  ('Route 66 Dog Park', 'At 1122 S Frankfort Ave, Route 66 Dog Park has 4.2 stars based on 36 reviews from Tulsa dog owners. This park provides dog owners in the community with a place to visit with their dogs. For pups who want more adventure, Veterans Park is a nearby dog park worth visiting (0.4 miles).', 36.1472951, -95.9813739, '1122 S Frankfort AveTulsa, Tulsa, OK 74120', 'Tulsa', 'OK', ARRAY[]::text[], false, false, false);
